#!/usr/bin/python3

import sys
import os
import re
import argparse, argcomplete
import requests
import subprocess
import shutil

from termcolor import colored, cprint
from collections import deque
from pathlib import Path

HOME = os.environ.get("HOME")
AUR_HOME = os.environ.get("AURHOME") if os.environ.get("AURHOME") else f'{HOME}/.local/share/aur'
AUR_URL = "https://aur.archlinux.org"

os.makedirs(AUR_HOME, exist_ok=True) if not os.path.exists(AUR_HOME) else ""

failed_packages = []

pacman_pkgs = []
aur_pkgs = []

def PkgCompleter(prefix, parsed_args, **kwargs):
    if parsed_args.clear_cache:
        path = Path(parsed_args.home_dir)
        dirs = [entry.name for entry in os.scandir(path) if entry.is_dir()]
        dir_dict = {}
        for d in dirs:
            dir_dict[d] = d
        
        return dir_dict

    return None

class PacmanPkgData:
    def __init__(self, name, is_dep=False):
        self.name = name
        self.is_dep = is_dep

    def __eq__(self, other):
        if isinstance(other, str):
            return self.name == other
        elif not isinstance(other, PacmanPkgData):
            return False
        return self.name == other.name

    def __hash__(self):
        return hash(self.name)

    def __repr__(self):
        return f"PacmanPkgData(name='{self.name}', is_dep='{self.is_dep}')"

class AurPkgData:
    def __init__(self, name, parent=None):
        self.name = name
        self.children = set()
        self.parent = parent

        if parent:
            parent.children.add(self)

    def __eq__(self, other):
        if isinstance(other, str):
            return self.name == other
        elif not isinstance(other, AurPkgData):
            return False
        return self.name == other.name

    def __hash__(self):
        return hash(self.name)

    def __repr__(self):
        return f"AurPkgData(name='{self.name}', parent='{self.parent.name if self.parent else 'None'}')"

class PackageException(Exception):
    pass

def package_queued(pkgname):
    for pkg in pacman_pkgs:
        if pkg.name == pkgname:
            return True
    for pkg in aur_pkgs:
        if pkg.name == pkgname:
            return True

def aur_exists(pkgname):
    url = f"{AUR_URL}/{pkgname}.git"
    
    response = requests.get(url)

    text_body = response.text
    return re.search(r"\bpkgbase\b", text_body) != None

def pacman_exists(pkgname):
    cmd = ['pacman', '-Si', pkgname]
    result = subprocess.run(cmd, capture_output=True, text=True)

    return result.returncode == 0

def package_installed(pkgname):
    cmd = ['pacman', '-Qi', pkgname]
    result = subprocess.run(cmd, capture_output=True, text=True)

    return result.returncode == 0

def aur_download(pkgname):
    cwd_path = f"{AUR_HOME}/{pkgname}"
    if os.path.exists(cwd_path):
        print(f"Updating {pkgname}...")
        cmd = ['git', 'pull']
        result = subprocess.run(cmd, cwd=cwd_path)
    else:
        cmd = ['git', 'clone', f"{AUR_URL}/{pkgname}.git"]
        result = subprocess.run(cmd, cwd=AUR_HOME)

def aur_build(pkgname, flags):
    cwd_path = f"{AUR_HOME}/{pkgname}"
    if not os.path.exists(cwd_path):
        return False
    else:
        cmd = ['makepkg', *flags.split(' ')]
        result = subprocess.run(cmd, cwd=cwd_path)
        return result.returncode == 0 or result.returncode == 13

def aur_get_tarball_path(pkgname):
    cwd_path = f"{AUR_HOME}/{pkgname}"
    if not os.path.exists(cwd_path):
        print(f"Failed to locate '{pkgname}' tarball")
        return ""
    else:
        cmd = ['makepkg', '--packagelist']
        result = subprocess.run(cmd, cwd=cwd_path, capture_output=True, text=True)
      
        tarball_re = r"\.tar\.[a-zA-Z]*$"
        for line in result.stdout.splitlines():
            if re.search(tarball_re, line):
                return line
    return ""


def aur_queue_deps(pkgname):
    cwd_path = f"{AUR_HOME}/{pkgname}"

    deps = []
    with open(f'{cwd_path}/.SRCINFO', "r") as f_srcinfo:
        body = f_srcinfo.read()

        dep_pat = r"\b(check|make)?depends\b *= *(.*)"
        for match in re.finditer(dep_pat, body):
            pkg = match.group(2)
            if package_installed(pkg):
                continue
            deps.append(pkg)

        optdep_pat = r"\boptdepends\b *= *([^:]*): *(.*)"
        for match in re.finditer(optdep_pat, body):
            optpkg = match.group(1)
            optdesc = match.group(2)

            if package_installed(optpkg):
                continue

            print(f"Install optional dependency '{optpkg}': {optdesc}\n")
            while True:
                choice = input("(y/n) > ")
                if choice == 'y':
                    deps.append(optpkg)
                    break
                elif choice == 'n':
                    break
            print()

             
    return deps

def queue_package(pkgname, preferred="pacman", parent=None):
    global pacman_pkgs
    global aur_pkgs

    if pkgname in pacman_pkgs or pkgname in aur_pkgs:
        return

    preferred = preferred.lower()

    choices = []

    if preferred == 'pacman':
        if pacman_exists(pkgname):
            pacman_pkgs.append(PacmanPkgData(pkgname, parent != None))
            return
        choices.append('AUR') if aur_exists(pkgname) else ""
    elif preferred == 'aur':
        if aur_exists(pkgname):
            aur_pkgs.append(AurPkgData(pkgname)) if not parent else aur_pkgs.insert(0, AurPkgData(pkgname, parent))

            return
        choices.append('Pacman') if pacman_exists(pkgname) else ""
    else:
        choices.append('Pacman') if pacman_exists(pkgname) else ""
        choices.append('AUR') if aur_exists(pkgname) else ""

    if len(choices) == 0:
        raise PackageException(f"package '{pkgname}' was not found")
    elif len(choices) == 1:
        if choices[0] == 'Pacman':
            pacman_pkgs.append(PacmanPkgData(pkgname)) if not parent else pacman_pkgs.insert(0, PacmanPkgData(pkgname, parent != None))
        elif choices[0] == 'AUR':
            aur_pkgs.append(AurPkgData(pkgname)) if not parent else aur_pkgs.insert(0, AurPkgData(pkgname, parent))
        else:
            raise PackageException(f"package '{pkgname}' was not found")
    else:
        choice=0
        print("Pick one of the following programs to install", end=" ")
        cprint(pkgname, attrs=["bold"])
        print()

        for i in range(len(choices)):
            print("%d)" % (i + 1), end=" ")
            cprint(choices[i], attrs=["bold"])
        print(f"\n(Default: {choices[0]})\n")

        while choice <= 0 or choice > len(choices):

            raw_choice = input("> ")
            try:
                choice = 1 if raw_choice == "" else int(raw_choice) 
            except ValueError:
                pass

def aur_gen_build_queue(pkg):
    children = pkg.children
    if len(children) == 0:
        return []

    queue = [children]
    for child in children:
        queue = [*aur_gen_build_queue(child), *queue]
   
    print(queue)
    return queue

def clear_cache(pkgs):
    print(f"AURHOME is set to '{AUR_HOME}'")
    if len(pkgs) == 0:
        path = Path(f'{AUR_HOME}')
        dirs = [p for p in path.iterdir() if p.is_dir()]
        
        if len(dirs) == 0:
            print("Nothing to do.")
            exit(0)

        dir_names = ' '.join([path.name for path in dirs])
        print(f'Remove directories? {dir_names}')
        while True:
            choice = input('(y/n) > ')
            if choice == 'y':
                for d in dirs:
                    shutil.rmtree(d)
                break
            elif choice == 'n':
                break
    else:
        for pkg in pkgs:
            validate_re = r"^ *\.\."
            if re.match(validate_re, pkg):
                print(f"'{pkg}' contains invalid sequence '..'")
                exit(1)
        dirs = [Path(f'{AUR_HOME}/{pkg}') for pkg in pkgs]
        for path in dirs:
            if not path.is_dir():
                print(f"'{path.name}' is not a valid directory")
                exit(1)
        
        if len(dirs) == 0:
            print("Nothing to do.")
            exit(0)

        dir_names = ' '.join([path.name for path in dirs])
        print(f'Remove directories? {dir_names}')
        while True:
            choice = input('(y/n) > ')
            if choice == 'y':
                for d in dirs:
                    shutil.rmtree(d)
                break
            elif choice == 'n':
                break

def aur_recurse_deps(preferred_installer):
    aur_dep_queue = deque(aur_pkgs)

    while len(aur_dep_queue) > 0:
        pkg = aur_dep_queue.popleft()
        aur_download(pkg.name)

        deps = aur_queue_deps(pkg.name)

        for dep in deps:
            if package_queued(dep):
                continue

            queue_package(dep, preferred=preferred_installer, parent=pkg)

            for p in aur_pkgs:
                if p.name == dep:
                    aur_dep_queue.appendleft(AurPkgData(dep, pkg))
                    break

def install_pacman_pkgs():
    pacman_deps = list(filter(lambda pkg: pkg.is_dep, pacman_pkgs))

    if len(pacman_pkgs) > 0:
        cmd = ["sudo", "pacman", "-S", *[pkg.name for pkg in pacman_pkgs]]
        print(' '.join(cmd))
        subprocess.run(cmd)

    if len(pacman_deps) > 0:
        cmd = ["sudo", "pacman", "-D", "--asdeps", *[pkg.name for pkg in pacman_deps]]
        print(' '.join(cmd))
        subprocess.run(cmd)

def install_aur_pkgs(flags):
    aur_parents = [pkg for pkg in aur_pkgs if pkg.parent == None]
    aur_build_queue = [aur_parents]
    for parent in aur_parents:
        aur_build_queue = [*aur_gen_build_queue(parent), *aur_build_queue]

    for deps in aur_build_queue:
        tarballs = []
        for dep in deps:
            if not aur_build(dep.name, flags):
                print(f"Failed to build {dep.name}")
                aur_pkgs.remove(dep)
                continue
            tarballs.append(aur_get_tarball_path(dep.name))
        if len(tarballs) > 0:
            cmd = ["sudo", "pacman", "-U", *tarballs]
            print(' '.join(cmd))
            subprocess.run(cmd)

    aur_deps = list(filter(lambda pkg: pkg.parent != None, aur_pkgs))
    if len(aur_deps) > 0:
        cmd = ["sudo", "pacman", "-D", "--asdeps", *[pkg.name for pkg in aur_deps]]
        print(' '.join(cmd))
        subprocess.run(cmd)

def gen_args():
    parser = argparse.ArgumentParser(
            prog="aur-make",
            description="AUR package installer alternative to yay"
            )
    parser.exit_on_error = True

    parser.add_argument('-p', '--preferred-installer', default="pacman", choices=['pacman','aur','none'])
    parser.add_argument('-cc', '--clear-cache', action="store_true")
    parser.add_argument('--home-dir', default=f"{AUR_HOME}")

    parser.add_argument('pkgs', nargs=argparse.REMAINDER).completer = PkgCompleter
    parser.add_argument('-D', dest="makepkg_flags", nargs="?", default="") 

    argcomplete.autocomplete(parser)
    return parser.parse_args()

if __name__ == "__main__":
    args = gen_args()

    AUR_HOME = args.home_dir
    
    if args.clear_cache:
        clear_cache(args.pkgs)
        exit(0)

    install_queue = args.pkgs
    for pkg in install_queue:
        queue_package(pkg, preferred=args.preferred_installer)

    aur_recurse_deps(args.preferred_installer)
    
    install_pacman_pkgs()
    install_aur_pkgs(args.makepkg_flags)

